import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-neutral-900 to-zinc-800`}>
      <Navbar />
        <div className="min-h-screen flex justify-center items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
